### ISSUE TITLE
Project Poster

### ISSUE THREAD

**Issue by swkoyo** [Secure-Password-Manager-Group/Secure-Password-Manager#27]
A poster assignment for our application

**Comment by LuisJSosa** [comment]
Poster Template: https://docs.google.com/presentation/d/1NGlOXDt5LcQi0UKoKxDLrCsymFhaQTImuvgV2LQ6cSE/edit#slide=id.p1

**Comment by BDixon808** [comment]
This looks good Luis, is there anything specific you wanted to add?
