### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by swkoyo** [Secure-Password-Manager-Group/Secure-Password-Manager#28]
It seems like the current deployment is broken. The link is returning a 404 error.  I think we just need to redeploy with the latest changes

LINK: https://secure-password-manager-group.uw.r.appspot.com/

**Comment by BDixon808** [comment]
Thinking about this, we might have to run a separate cloud instance for the front end and backend. 
I think the 404 is because the deployment has not been updated.
